name: Test
on: push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup

      - name: Run Lint
        run: pnpm lint

      - name: Build
        run: pnpm build

      - name: Check working copy
        run: git diff --exit-code

      - name: Run TurboRepo Remote Cache Server
        uses: ./
        with:
          storage-provider: local
          storage-path: test
          port-retry-time-ms: 500
          port-timeout-ms: 10000
      
      - name: Ensure environmental variables have been set correctly
        run: |
          echo $TURBO_API | grep -P "^http://127.0.0.1:\d+$"
          echo $TURBO_TOKEN | grep -P "^[a-zA-Z0-9]{48}$"
          echo $TURBO_TEAM | grep -P "^ci$"